@startuml
actor Usuario
boundary usuario.routes as Routes
boundary usuario.jsx as usuarioView
boundary registrar_usuario.jsx as View
boundary componente_usuario.jsx as ViewComponent
control usuario.controller as Controller
entity usuario.model as Model
database Database

    Usuario -> Routes: GET /usuario/registrar_usuario
    activate Routes
    Routes -> Controller: get_registrar_usuario\n(request, response, next)
    deactivate Routes
    activate Controller
    Controller ->> Model: usuario.fetchAll
    activate Model
    Model ->> Database: SELECT * FROM usuario
    activate Database
    Database -->> Model: DATA[]
    deactivate Database
    Model -->> Controller: PROMESA
    deactivate Model
    Controller -> View: response.render("registrar_usuario",\n{ usuario })
    deactivate Controller
    activate View
    View -->> Usuario: HTTP 200 OK
    deactivate View

    activate Usuario
    Usuario -> ViewComponent: Registrar Usuario
    deactivate Usuario
    activate ViewComponent
    ViewComponent -> ViewComponent: validarCampos(datosUsuario)

    alt Datos Incompletos
        ViewComponent -->> Usuario: Mostrar mensaje:\n"Por favor llena todos los campos"
    end

    ViewComponent -> Routes: POST /usuario/anadir\n{ nombre, correo, contraseña, is_user_admin, estatus_usuario }
    deactivate ViewComponent
    activate Routes
    Routes -> Controller: post_registrar_usuario(request, response, next)
    deactivate Routes
    activate Controller
    Controller ->> Model: usuario.anadir\n({usuario})
    activate Model
    Model ->> Database: INSERT INTO usuario\n(id_usuario, ...)
    activate Database
    Database -->> Model: SUCCESS / ID GENERADO
    deactivate Database
    Model -->> Controller: PROMESA
    deactivate Model

    alt Error al anadir
        Controller -> Routes: response.redirect(/usuario)
        activate Routes
        Routes -->> Usuario: HTTP 500 Internal Server Error
        deactivate Routes
    end

    Controller -> Routes: response.redirect(/usuario)
    deactivate Controller
    activate Routes
    Routes -> Controller: get_usuario(request, response, next)
    deactivate Routes
    activate Controller
    Controller -> usuarioView: response.render('usuario')
    deactivate Controller
    activate usuarioView
    usuarioView -->> Usuario: HTTP 201 Created
    deactivate usuarioView

@enduml
