@startuml NavBar
actor Usuario as user
boundary MainLayout as layout
collections App.jsx as routes
collections Backend as back

/'actor nav route cont rout '/

activate user
    user -> layout: 1.- Petición de ruta
deactivate user

activate layout
    layout -> routes: 2.- <Outlet /> llama a la ruta
deactivate layout

activate routes
    routes -> back: 3.- Hace peticiones correspondientes
    activate back
        back -> routes: 4.- JSON
    deactivate back
    routes -> layout: 4.- HTML renderizado en <Outlet />
deactivate routes



@enduml